version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-koxmf8uyadzd"
s3_prefix = "sam-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ConnectionsTableName=\"nordchat_connections\" UsersTableName=\"nordchat_users\""
image_repositories = []
